version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    environment:
      # For write permission in /games directory
      - PUID=1000
      - PGID=1000
      # Uncomment to setup basic auth
      # - USERNAME=a1ex
      # - PASSWORD=
      # - ROOT_DIR=/games
      # - SAVE_ENABLED=true
    volumes:
      - /your/game/directory:/games
      - /your/config/directory/:/config
    ports:
      - "8000:80"